# Generated by Django 4.0.2 on 2022-06-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods_and_services',
            table=None,
        ),
        migrations.AlterModelTable(
            name='passengers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purch_goods_services',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purch_tickets',
            table=None,
        ),
        migrations.AlterModelTable(
            name='routes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trains',
            table=None,
        ),
    ]
