# Generated by Django 4.0.2 on 2022-06-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goods_and_services_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purch_tickets',
            name='id_passengers',
        ),
        migrations.RemoveField(
            model_name='purch_tickets',
            name='id_train',
        ),
        migrations.AlterModelTable(
            name='goods_and_services',
            table='content"."goods_and_services',
        ),
        migrations.AlterModelTable(
            name='passengers',
            table='content"."passengers',
        ),
        migrations.AlterModelTable(
            name='routes',
            table='content"."routes',
        ),
        migrations.AlterModelTable(
            name='trains',
            table='content"."trains',
        ),
        migrations.DeleteModel(
            name='Purch_goods_services',
        ),
        migrations.DeleteModel(
            name='Purch_tickets',
        ),
    ]
