# Generated by Django 4.0.2 on 2022-06-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_purch_tickets_id_passengers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods_and_services',
            table='recsys"."goods_and_services',
        ),
        migrations.AlterModelTable(
            name='passengers',
            table='recsys"."passengers',
        ),
        migrations.AlterModelTable(
            name='routes',
            table='recsys"."routes',
        ),
        migrations.AlterModelTable(
            name='trains',
            table='recsys"."trains',
        ),
    ]
