# Generated by Django 4.0.2 on 2022-06-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_goods_and_services_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods_and_services',
            table='content"."goods_and_services',
        ),
        migrations.AlterModelTable(
            name='passengers',
            table='content"."passengers',
        ),
        migrations.AlterModelTable(
            name='routes',
            table='content"."routes',
        ),
        migrations.AlterModelTable(
            name='trains',
            table='content"."trains',
        ),
    ]
