# Generated by Django 4.0 on 2022-07-05 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_and_services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.IntegerField(blank=True, verbose_name='price')),
                ('age_0_5', models.BooleanField(blank=True, verbose_name='age_0_5')),
                ('age_6_10', models.BooleanField(blank=True, verbose_name='age_6_10')),
                ('age_11_17', models.BooleanField(blank=True, verbose_name='age_11_17')),
                ('age_18_55', models.BooleanField(blank=True, verbose_name='age_18_55')),
                ('age_56_90', models.BooleanField(blank=True, verbose_name='age_56_90')),
                ('type_service', models.BooleanField(blank=True, verbose_name='type_service')),
                ('kind_hygiene', models.BooleanField(blank=True, verbose_name='kind_hygiene')),
                ('kind_road_equipment', models.BooleanField(blank=True, verbose_name='kind_road_equipment')),
                ('kind_relax', models.BooleanField(blank=True, verbose_name='kind_relax')),
                ('kind_food', models.BooleanField(blank=True, verbose_name='kind_food')),
                ('available_coupe', models.BooleanField(blank=True, verbose_name='available_coupe')),
                ('available_plaz', models.BooleanField(blank=True, verbose_name='available_plaz')),
            ],
            options={
                'verbose_name': 'goods_and_services',
                'verbose_name_plural': 'goods_and_services',
                'db_table': 'goods_and_services',
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=255, verbose_name='sex')),
                ('age', models.IntegerField(blank=True, verbose_name='age')),
                ('marit_status', models.CharField(max_length=255, verbose_name='marit_status')),
                ('education', models.CharField(max_length=255, verbose_name='education')),
                ('childs', models.IntegerField(blank=True, verbose_name='childs')),
                ('networks_fb', models.BooleanField(blank=True, verbose_name='networks_fb')),
                ('networks_inst', models.BooleanField(blank=True, verbose_name='networks_inst')),
                ('networks_tt', models.BooleanField(blank=True, verbose_name='networks_tt')),
                ('networks_vk', models.BooleanField(blank=True, verbose_name='networks_vk')),
                ('networks_ok', models.BooleanField(blank=True, verbose_name='networks_ok')),
            ],
            options={
                'verbose_name': 'passengers',
                'verbose_name_plural': 'passengers',
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=255, verbose_name='start')),
                ('route_time', models.IntegerField(blank=True, verbose_name='route_time')),
                ('end', models.CharField(max_length=255, verbose_name='end')),
            ],
            options={
                'verbose_name': 'routes',
                'verbose_name_plural': 'routes',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_trains', models.CharField(max_length=255, verbose_name='num_trains')),
                ('time_departure', models.IntegerField(blank=True, verbose_name='time_departure')),
                ('time_arrival', models.IntegerField(blank=True, verbose_name='time_arrival')),
                ('plaz_count', models.IntegerField(blank=True, verbose_name='plaz_count')),
                ('coupe_count', models.IntegerField(blank=True, verbose_name='coupe_count')),
                ('sv_count', models.IntegerField(blank=True, verbose_name='sv_count')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='app.routes', verbose_name='routes')),
            ],
            options={
                'verbose_name': 'trains',
                'verbose_name_plural': 'trains',
                'db_table': 'trains',
            },
        ),
        migrations.CreateModel(
            name='Purch_tickets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_wagon', models.CharField(max_length=255, verbose_name='type_wagon')),
                ('num_wagon', models.IntegerField(blank=True, verbose_name='num_wagon')),
                ('num_seat', models.IntegerField(blank=True, verbose_name='num_seat')),
                ('price', models.FloatField(blank=True, verbose_name='price')),
                ('dates_purchase', models.DateTimeField()),
                ('passengers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='app.passengers', verbose_name='passengers')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='app.trains', verbose_name='train')),
            ],
            options={
                'verbose_name': 'purch_tickets',
                'verbose_name_plural': 'purch_tickets',
                'db_table': 'purch_tickets',
            },
        ),
        migrations.CreateModel(
            name='Purch_goods_services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs', to='app.goods_and_services', verbose_name='gs')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='app.purch_tickets', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'purch_goods_services',
                'verbose_name_plural': 'purch_goods_services',
                'db_table': 'purch_goods_services',
            },
        ),
    ]
